CMake: require C++ 14
to fix on macos 14 / boost 1.87:
```
        …/cmeel.prefix/include/boost/smart_ptr/bad_weak_ptr.hpp:36:18: error: exception specification of overriding function is more lax than base version
            char const * what() const noexcept override
                         ^